In [3]:
from FinMind.data import DataLoader
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei']
# plt.rcParams['font.sans-serif'] = ['Arial Unicode Ms']

api = DataLoader()

In [4]:
# 取出台灣股市 ETF
df = api.taiwan_stock_info()

2024-11-29 15:26:22.021 | INFO     | FinMind.data.finmind_api:get_data:125 - download Dataset.TaiwanStockInfo, data_id:

In [10]:
Bond_dataframe = df[
    (df["stock_id"].str.contains("U"))
]
Bond_dataframe

    industry_category stock_id stock_name  type        date
24                ETF   00635U   期元大S&P黃金  twse  2024-11-28
32                ETF   00642U   期元大S&P石油  twse  2024-11-28
69                ETF   00677U     期富邦VIX  twse  2024-11-28
74                ETF   00682U    期元大美元指數  twse  2024-11-28
85                ETF   00693U   期街口S&P黃豆  twse  2024-11-28
130               ETF   00738U    期元大道瓊白銀  twse  2024-11-28
155               ETF   00763U     期街口道瓊銅  twse  2024-11-28

In [11]:
ETF_dataframe = df[
    (df["industry_category"].str[:3] == "ETF")
    & (df["stock_name"].str.contains("元大"))
    & (df["stock_id"].str[-1].str.isnumeric())
]
ETF_dataframe

    industry_category stock_id stock_name  type        date
0                 ETF     0050     元大台灣50  twse  2024-11-28
1                 ETF     0051    元大中型100  twse  2024-11-28
3                 ETF     0053       元大電子  twse  2024-11-28
4                 ETF     0054     元大台商50  twse  2024-11-28
5                 ETF     0055   元大MSCI金融  twse  2024-11-28
6                 ETF     0056      元大高股息  twse  2024-11-28
11                ETF     0061      元大寶滬深  twse  2024-11-28
13                ETF   006203   元大MSCI台灣  twse  2024-11-28
16                ETF   006206     元大上證50  twse  2024-11-28
36                ETF    00646   元大S&P500  twse  2024-11-28
51                ETF    00660     元大歐洲50  twse  2024-11-28
52                ETF    00661    元大日經225  twse  2024-11-28
58                ETF    00667       元大韓國  twse  2024-11-28
105               ETF    00713   元大台灣高息低波  twse  2024-11-28
131               ETF    00739  元大MSCI A股  twse  2024-11-28
154               ETF    00762     元大全球AI  twse  2024-11-28
162               ETF    00771  元大US高息特別股  twse  2024-11-28
214               ETF    00850  元大臺灣ESG永續  twse  2024-11-28
225               ETF    00861   元大全球未來通訊  twse  2024-11-28
240               ETF    00876     元大全球5G  twse  2024-11-28
303               ETF    00940   元大台灣價值高息  twse  2024-11-28
327               ETF    00965   元大航太防衛科技  twse  2024-11-28

In [ ]:
# 永久投資組合
portfolio = {
    "VTI": 0.25,  # 股票 25%
    "TLT": 0.25,  # 長期債券 25%
    "SHY": 0.25,  # 現金選擇 25%
    "GLD": 0.25,  # 貴金屬 25%
}

# 全天候資產配置
portfolio = {
    "VTI": 0.3,  # 股票 30%
    "TLT": 0.40,  # 長期債券 40%
    "IEF": 0.15,  # 中期債券 15%
    "DBC": 0.075,  # 原物料 7.5%
    "GLD": 0.075,  # 貴金屬 7.5%
}