# GCP VM MariaDB 資料庫連線語法大全

這個 Jupyter Notebook 提供使用 Python 連線到 GCP VM 上 MariaDB 資料庫的完整範例。

## 環境準備
- 需要安裝的套件：`pip install mysql-connector-python pandas sqlalchemy`
- 支援操作：連線、查詢 (SELECT)、插入 (INSERT)、更新 (UPDATE)、刪除 (DELETE)、交易處理等。
- 注意事項：
  - 確保 GCP VM 的防火牆允許 3306 連接埠。
  - 替換以下連線資訊為您自己的。
  - DATABASE 和 TABLE 可以根據需要修改。

In [5]:
# ==================== 1. 導入必要套件 ====================
# mysql-connector-python: 用於直接連線 MariaDB
# pandas: 用於資料讀取與處理
# sqlalchemy: 用於更高階的資料庫操作（如 pandas.to_sql）
import mysql.connector
from mysql.connector import Error
import pandas as pd
from sqlalchemy import create_engine, text
from datetime import datetime

In [6]:
# ==================== 2. 設定連線參數 ====================
# 使用外部設定檔 db_config.py
try:
    from db_config import DB_HOST, DB_USER, DB_PASSWORD, DB_NAME
except ImportError:
    print("錯誤：找不到 db_config.py")
    # 如果找不到，這裡可以留空或拋出錯誤
    DB_HOST, DB_USER, DB_PASSWORD, DB_NAME = '', '', '', ''
HOST = DB_HOST
USER = DB_USER
PASSWORD = DB_PASSWORD
DATABASE = DB_NAME
# TABLE 保留為原本的設定或不變

# 建立 SQLAlchemy 引擎（用於 pandas 操作）
engine = create_engine(f'mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}:3306/{DATABASE}')

# 測試連線是否成功
try:
    with engine.connect() as conn:
        print(f"成功連線到資料庫: {DATABASE} on {HOST}")
except Error as e:
    print(f"連線失敗: {e}")

成功連線到資料庫: rawdata on 35.185.175.249

## 範例 1: 基本連線與斷開連線

使用 `mysql.connector` 建立連線，並確保斷開連線。

In [ ]:
# ==================== 範例 1: 基本連線與斷開 ====================
try:
    # 建立連線
    conn = mysql.connector.connect(
        host=HOST,
        user=USER,
        password=PASSWORD,
        database=DATABASE
    )
    
    if conn.is_connected():
        print("連線成功！")
        cursor = conn.cursor()  # 建立游標，用於執行 SQL
        cursor.execute("SELECT VERSION()")  # 查詢 MariaDB 版本
        version = cursor.fetchone()
        print(f"MariaDB 版本: {version[0]}")
    
except Error as e:
    print(f"連線錯誤: {e}")
finally:
    if 'conn' in locals() and conn.is_connected():
        cursor.close()  # 關閉游標
        conn.close()    # 關閉連線
        print("連線已關閉")

## 範例 2: 查詢資料 (SELECT)

- 使用直接 SQL 查詢。
- 使用 pandas 讀取查詢結果。

In [4]:
TABLE = 'job_details'

# ==================== 範例 2.1: 使用 mysql-connector 執行 SELECT ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    # SQL 查詢語法（可修改條件）
    query = f"SELECT * FROM {TABLE} LIMIT 5"  # 查詢前 5 筆資料
    cursor.execute(query)
    
    # 取得結果
    results = cursor.fetchall()
    for row in results:
        print(row)  # 印出每一行資料
    
except Error as e:
    print(f"查詢錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

(1, 'https://www.cake.me/companies/commeet/jobs/data-assistant-engineerdata-science-intern', '數據工程師實習生 Data Engineer Intern', 'COMMEET＿擁樂數據服務股份有限公司', '軟體', '數據工程師', '200 ~ 250 TWD / 小時', '台北市, 台灣', '經驗不拘', '實習生', '初階', '1', '不需負擔管理責任', '不支援遠端', '松山區長安東路二段225號A棟1樓之1, 松山區, 台北', 'python, postgres, redis, git', '職缺 1 天前更新', 'COMMEET (https://commeet.co) 擴大徵才，歡迎有熱情之新夥伴加入我們的行列\n[工作內容]\n1 整理、標記數據，以確保數據的準確性與可靠性。\n2 訓練OCR模型，並進行模型效能評估。\n3 建立/維護/優化資料處理流程與架構(data pipeline)。\n4 從業人員恪守客戶個資保護敏感度及尊重客戶資料隱密性。\n5 其它主管交辦事項。\n[職缺條件]\n• 熟悉 ML/DL\n• 熟悉 python 語言與相關資料庫 (csv、postgres、redis、excel)\n• 熟悉 git 版本控制\n• 入職3個月內需通過公司內部程式能力測驗(實習生需刷題75題以上)\n[排班說明]\n• 非寒暑假短期性質必須配合「實習達六個月」。\n• 比照公務機關行事曆出勤，一週達24小時，須至辦公室出勤。\n• 每月雙方協商排定班表，若無法約定班表出勤，須提前溝通調整班表。\n• 出勤工作日排班最小單位為一個時段 (選上半天時段/下半天時段/全日時段)。\n- 全日班表定工作時間 09:30 ~18:30，可彈性於 09:00 ~ 10:00 間簽到上班，午休時段可選擇12:00-13:00 或 12:30-13:30，每日正常工作時間不超過八小時。\n- 09:30 ~ 13:30 上半天工作時段 (上班有彈性工時)，工作四小時(含)則不會有休息。\n- 14:30 ~ 18:30 下半天工作時段 (上班無彈性工時)，工作四小時(含)則不會有休息。\n初試：線上面試，請您提前準備自我介紹簡報，有效率的讓我們認識您 (使用電腦分享畫面即可，10分鐘)➡用人單位/30分鐘。\n複試：若初試後雙方若有交集，會另約其他日期複試 / 複試前請先準備指定主題內容➡用人主管/團隊成員60~90分鐘。\n擁樂數據服務擁有專業的資訊開發團隊，深度經營 B2B 市場，提供企業客戶最智慧的營運管理解方。\n2020 年擁樂數據推出全新 B2B SaaS 品牌「COMMEET 智能費用管理系統」，致力於成為台灣企業數位轉型推動者，我們從財務流程出發，協助企業更有效率的達成營運管理目標。', datetime.datetime(2025, 12, 5, 10, 38, 25))
(2, 'https://www.cake.me/companies/pinkoi/jobs/b2ec807e-05ce-449b-bd06-42404466362d-data-engineer-10e1700edfb1a970396752254773d1', 'Data Engineer', 'Pinkoi', '其他', '其他', '800,000 ~ 1,500,000 TWD / 年', '台北市, 台灣', '經驗不拘', '全職', '中高階', '1', '不需負擔管理責任', '不支援遠端', '', 'python, java, scala, mysql, bigquery, spark, hadoop, hive, dbt, aws, gcp, linux, tableau, looker, superset', '職缺 7 天前更新', '【關於 Pinkoi Data Squad】\n我們是 Pinkoi 的資料團隊，其目標為打造有效的數據平台，同時確保資料的品質與穩定性，讓資料在 Pinkoi 發揮最大的價值。Data Engineer 將與 Business Analyst／ML Engineer 緊密合作，透過數據探索問題、規劃後續的 Data Pipeline（資料管線） 實作，並提供 End-to-end 的 Data Solution，以擴展公司各部門的數據分析能力，並完善整體商業智慧系統。\n你需要負責的工作內容\n與產品、行銷、廣告等分析師與商業團隊合作，理解需求並規劃合適的 Data Pipeline。\n設計、實作與維護 ETL/ELT 流程，確保資料品質、穩定性與新鮮度。\n建立與優化資料模型，支援報表、分析與機器學習等多種場景。\n持續迭代並優化資料基礎建設，提升可擴展性與維運效率。\n建立監控與告警機制，確保 Pipeline 成功率與資料 SLA。\n我們希望你有的經驗跟特質\n對 Big Data 和 Data-driven engineering 有極大的熱情。\n瞭解 ETL 或 ELT 的流程，並具備 Data Modeling 跟開發 Data Pipeline 的能力。\n具備與產品 / 行銷團隊合作的經驗，並可與商業分析師、資料工程師，以及機器學習工程師協同合作。\n樂於學習最新的技術，隨時充實自我的專業技能。\n對大型語言模型（LLM）保持開放與好奇，願意學習並嘗試將其應用於資料工程工作（如：資料清理、欄位補全、文件生成、自動化測試），以探索新工具如何提升效率與使用者體驗。\n應徵條件\n數學 / 統計 / 資訊 / 資料科學相關科系畢業，或具備同等專業能力。\n一年以上數據分析或數據工程相關工作經驗。\n熟悉 Python、Scala、Java 等任何一種程式語言，Pinkoi 主要用 Python。\n熟悉 GNU/Linux 系統，Pinkoi 用 Ubuntu。\n熟悉關聯式資料庫的運用，例如 MySQL。\n加分條件\n熟悉廣告歸因邏輯，或具備相關數據處理經驗。\n具備使用者行為數據處理經驗。具有操作或架設 BI 工具的相關經驗。\n如 Superset、Tableau、Looker Studio，Pinkoi 使用 Superset 和 Redash。\n具有分散式運算的相關知識，例如 Spark、Hadoop、Hive 等一種或多種相關技術，Pinkoi 主要用 PySpark。\n熟悉雲端服務，例如 AWS Athena、S3、Glue，GCP BigQuery 等，Pinkoi 主要用 AWS。\n了解 dbt 的基礎架構和應用方式，如建立資料模型、撰寫測試、建立巨集等等。\n有將 LLM 應用於資料工程場景的經驗，例如規則抽取、欄位對齊與補全、文件／Data Catalog 生成、資料品質檢查等。\n＃不用想了，趕快來當個 Pinkoi 人\n如果你有信心能夠勝任這份工作，歡迎提供你的個人履歷與小作業，即刻應徵！\n❋ 歡迎點擊頁面右上角追蹤鍵，以獲得 Pinkoi 最新的職缺資訊！❋\nPinkoi 集團\nPinkoi 以茁壯亞洲設計生態圈為品牌使命，從台北出發，並陸續在東京、香港、曼谷、上海等地設立據點，以 AI 與大數據技術為根本，以跨境電商平台為基底，加上 SaaS 服務、實體展會活動等 OMO 管道提供設計品牌成長和國際拓展所需的養分，並期許為市場帶來更多國際級的設計品牌，為市場創造更多優質消費品牌的選擇，期望在每個送禮過節和值得紀念，都能用好設計滿足大眾對品味生活的嚮往。\nPinkoi.com 設計購物平台\nPinkoi.com\xa0是亞洲跨境設計購物平台，販售設計商品、數位創作、體驗活動，商品涵蓋食衣住行育樂，並網羅海內外優質設計師群，堅持用好品味、客製化的獨特設計，讓每個人用好設計慶祝生活中的大小時刻，並將設計成為生活日常。\n2011 年 8 月成立至今，致力於經營亞洲市場，期望讓迷人的好設計在全世界散發光芒，並創造一個讓生活更美好的設計生態圈。', datetime.datetime(2025, 12, 5, 10, 38, 29))
(3, 'https://www.cake.me/companies/7-eleven-vietnam/jobs/data-engineer-intern-b66', 'Data Engineer Intern', '7-ELEVEN VIETNAM', '軟體', '數據工程師', None, 'Vietnam,Ho Chi Minh City, Vietnam', '經驗不拘', '全職', '未標示', '1', '不需負擔管理責任', '不支援遠端', '', 'python, r, sql, airflow, google cloud, docker, kubernetes', '職缺 7 天前更新', 'Salary:\nNegotiation\nLocation:\n7-Eleven Head Office\nApplication deadline:\n20/11 — 20/12/2025\nHeadquarter Address: 7th Floor, Cobi Tower 2, No. 2-4, Street 8, Tan My Ward, Ho Chi Minh City\nAs a Data Engineer Intern, you will work closely with our data engineering team to support and contribute to various data-related projects. Your responsibilities will include:\nData Pipeline Development: Collaborate with the data engineering team to build, maintain, and optimize data pipelines for processing and transferring data from various sources to storage and analytical systems\nData Integration: Assist in integrating data from different sources (e.g., databases, APIs, flat files) into our data ecosystem, ensuring data accuracy, quality, and consistency\nDatabase Management: Work on creating and maintaining databases, ensuring data storage and retrieval efficiency, and implementing data security measures\nData Transformation: Help transform and clean data to make it suitable for analysis, reporting. This may involve using ETL (Extract, Transform, Load) processes\nResearch and Learning: Stay up-to-date with the latest data engineering technologies and best practices and actively participate in ongoing learning and skill development.\nMore details will be discussed at the interview.\nWe are cool\nDeveloping the Retail Management System helps 7-Eleven Vietnam to save cost and earn money such as Ecommerce Website, Loyalty Application, Supply Chain System, Warehouse Management System, Payment Gateway, POS, HHT,...\nBuilding a loyalty application with React Native\nBuilding an ecommerce website\nModern tech stack (Google Cloud Platform, Docker, Kubernetes, Rancher) and tools (Google Chat, Jira)\nCatching up with new technologies through the process: experiment, trial, adopt\nIn partnership with Grab, ZaloPay, Momo, VnPay, Airpay, ShopeeFood, GrabMart, GotIt, TAPTAP, Vani,  Google for tech & digital integrations\nAgile at heart, everything is flexible and possible\nFlat team, nice colleagues, no boss\nStrong engineering culture, read more of our stories on 7-Eleven Viet Nam Engineering Blog\nAnd some benefits\nInternship allowance\nThe flexible working environment in terms of time, office\nChances for training and development (learning out-door, training course, soft skills)\nBachelor‘s in a related field (Computer Science, Data Science, Information Systems, etc.)\nBasic understanding of database concepts, SQL, and data modeling.\nExperience in Airflow or any ETL/Orchestration tool is a plus\nExperience in Python or R is a big plus\nStrong interest in data engineering and a willingness to learn and apply new technologies and tools\nStrong communication and teamwork skills\nThe ability to work independently and take initiative\nWHO ARE WE?\nAs the world’s leading convenience store chain, we know that our people are the key to sustain success. We strive to create an innovative, engaging and fulfilling environment where everyone is equipped with the skills to lead and inspire excellence in others.\nWHY JOIN US?\nChallenging Career\nWe believe that empowering employees is the kind of investment that yields the highest returns. At 7-Eleven, you do not just work for the firm, you grow with it.\nCompetitive Compensation and Benefits\nFrom assigning mentors to arranging training opportunities, we enable employees to reach their full potential. We also work hard to ensure that our employees are compensated fairly and aim to provide highly competitive pay levels over the long term.\nYoung and Dynamic Team\nIn addition to rewarding benefits, we help each employee to realize their values so that everyone works together to overcome challenges and to build a positive culture.', datetime.datetime(2025, 12, 5, 10, 38, 40))
(4, 'https://www.cake.me/companies/WorldQuant/jobs/4607049006-data-engineer-8207e93ed0b79a6e5296899e2822d0', 'Data Engineer', 'WorldQuant', '其他', '其他', None, 'Hanoi, Vietnam,Ho Chi Minh City, Vietnam', '經驗不拘', '全職', '中高階', '1', '不需負擔管理責任', '不支援遠端', '', 'python, kubernetes, git, shell', '職缺大約 8 小時前更新', "WorldQuant develops and deploys systematic financial strategies across a broad range of asset classes and global markets. We seek to produce high-quality predictive signals (alphas) through our proprietary research platform to employ financial strategies focused on market inefficiencies. Our teams work collaboratively to drive the production of alphas and financial strategies – the foundation of a balanced, global investment platform.\nWorldQuant is built on a culture that pairs academic sensibility with accountability for results. Employees are encouraged to think openly about problems, balancing intellectualism and practicality. Excellent ideas come from anyone, anywhere. Employees are encouraged to challenge conventional thinking and possess an attitude of continuous improvement.\nOur goal is to hire the best and the brightest. We value intellectual horsepower first and foremost, and people who demonstrate an outstanding talent. There is no roadmap to future success, so we need people who can help us build it.\nTechnologists at WorldQuant research, design, code, test and deploy firmwide platforms and tooling while working collaboratively with researchers. Our environment is relaxed yet intellectually driven. We seek people who think in code and are motivated by being around like-minded people.\nThe Role:\nWe are looking for an experienced Data Engineer who will help us to build and maintain an ecosystem for processing multiple datasets from different sources (both internal and external) vital to the firm’s investment operations.\nWhat You'll Do:\nCreating automated data processing system and monitoring/maintaining it\nIntegrating multiple data sources and databases into one system\nDeveloping interfaces and micro services in Python\nEnriching company’s data\xa0by applying NLP and AI models\nPreprocessing and cleansing of semi-structured or unstructured data\nDeveloping efficient algorithms for data processing\nTesting and integrating external APIs\nSupporting Business Analysts team\nWhat You’ll Bring:\nA bachelor / master's degree in a technical or quantitative field from top university\nAt least 3 years of experience as a data engineer or software developer\nExcellent programming skills\nExperience with data processing using Python\nExperience with building databases\nExperience with Containers and Kubernetes\nScripting skills in UNIX environment: shell, python Fire, etc.\nExperience with code versioning tools (e.g. Git), issue tracking tools (e.g. Jira)\nDebugging skills, eye for detail and identifying problems\nStrong problem-solving skills and an analytical mindset\nA passion for working with data\nWhat We Offer:\nCompetitive and attractive compensation package with clear career road-map – where you feel challenged everyday\nWe offer a strong culture of learning and development: training courses, library, speakers, share and learn events\nLearn from who sits next to you! Working in WQ you are surrounded by smart and talented people\nPremium Health Insurance and Employee Assistance Program\nGenerous time-off policy, re-creation sabbatical leave (based on tenure), Trade Union benefits for staff and family\nTeam building activities every month: Local engagement events, monthly team lunch – Employee clubs: football, ping-pong, badminton, yoga, running, PS5, movies, etc.\nAnnual company trip and occasional global conferences – opportunity to travel and connect with our global teams\nHappy-hour with tea break, snacks and meals every day in the office!\n#LI-VP1\nBy submitting this application, you acknowledge and consent to terms of the\nWorldQuant Privacy Policy.\nThe privacy policy offers an explanation of how and why your data will be collected, how it will be used and disclosed, how it will be retained and secured, and what legal rights are associated with that data (including the rights of access, correction, and deletion). The policy also describes legal and contractual limitations on these rights. The specific rights and obligations of individuals living and working in different areas may vary by jurisdiction.\nCopyright © 2025 WorldQuant, LLC. All Rights Reserved.\nWorldQuant is an equal opportunity employer and does not discriminate in hiring on the basis of race, color, creed, religion, sex, sexual orientation or preference, age, marital status, citizenship, national origin, disability, military status, genetic predisposition or carrier status, or any other protected characteristic as established by applicable law.\nWorldQuant\xa0是家全球量化資產管理公司，管理超過\xa070\xa0億美元的資產。由\xa0Igor Tulchinsky\xa0於\xa02007\xa0年創立，我們相信人才遍布全球，但機會則非如此，目前擁有超過\xa01000\xa0名員工、分布在全球\xa026\xa0個辦公室。我們遵循著有無限洞見可以發掘的原則，試圖更快速地走向未來，WorldQuant 針對國際市場上不同的資產類別建制及應用系統性的金融策略。\n想了解更多關於 WorldQuant 的經營理念與文化，請造訪\nwww.worldquant.com\nWorldQuant\xa0is a global quantitative asset management firm with over $7 billion in assets under management. Founded in 2007 by Igor Tulchinsky with the belief that talent is global, but opportunity is not,\xa0WorldQuant\xa0has more than 1,000 employees spread among 26 global offices.\xa0WorldQuant\xa0seeks to get to the future faster, guided by the principle that there are an infinite number of insights to discover. The firm develops and deploys investment strategies across a variety of asset classes in global markets. For more information on\xa0WorldQuant’s philosophy and culture, please visit\nwww.worldquant.com\n.", datetime.datetime(2025, 12, 5, 10, 38, 44))
(5, 'https://www.cake.me/companies/opennet-limited/jobs/data-engineer-99f', 'Data Engineer', 'OpenNet 開網有限公司', '軟體', '數據工程師', '800,000 ~ 1,700,000 TWD / 年', '台北市, 台灣', '需具備 2 年以上工作經驗', '全職', '中高階', '1', '不需負擔管理責任', '選擇性或彈性遠端工作', '', 'python, mysql, mongodb, redshift, airflow, aws, shell', '職缺 13 天前更新', 'If You Are\n● The successful candidate will be a self-driven person with proven experience in\nlarge-scale RDBMS and data warehouse\n● The candidate will have a deep understanding of MySQL and MongoDB\n● The candidate will be familiar with data model, schema and ETL processes design pattern.\nWho We Are\nOpenNet is one of the best companies to work for in Taiwan; we offer a dynamic and rewarding environment for high-achievers looking to work and learn alongside like-minded individuals. We are currently in a period of rapid growth as we expand to make our technology available in over 20 countries.\nWe believe our employees are the company’s most valuable asset and are invested in seeing our employees grow in their careers and strike a work-life balance. We do our best to attract top talent and create a great workplace where people feel engaged, inspired, challenged, and respected.\nOur Stack\nCore:\n● Database: MySQL, MongoDB\n● PaaS: AWS RDS, Redshift, MongoDB Atlas\nPlus:\n● Business Monitoring: PMM\n● Cloud Services: AWS EC2, Cloudwatch, Secrets Manager, etc.\n● ETL & presentation: airflow, metabase.\n● Server Operating System: CentOS\nKey Responsibilities\n● Manage MySQL & MongoDB databases\n● Refine data model & ETL processes in Redshift data warehouse\n● Cowork with developer to optimize the schema design & queries\n● 3+ years of specific experience with MySQL and MongoDB administration for large-scale\nsystems\n● Experience on AWS RDS, Redshift, EC2, CloudWatch, and MongoDB Atlas\n● Solid hand on experience on python or shell scripting\n● Familiar with ETL tools\n● Fluent in listening, speaking, reading and writing English\n● Openmind and willing to take new challenges\n1. Online test: 120 mins\n2. Onsite interview: 100 mins\n3. Interview result within 24 hrs\nOpenNet is one of the best companies to work for in Taiwan; we offer a dynamic and rewarding environment for high-achievers looking to work and learn alongside like-minded individuals. We are currently in a period of rapid growth as we expand to make our technology available in over 20 countries.\nWe believe our employees are the company’s most valuable asset and are invested in seeing our employees grow in their careers and strike a work-life balance. We do our best to attract top talent and create a great workplace where people feel engaged, inspired, challenged, and respected.\nIf you are forward-thinking, passionate about technology, enjoy a fast-paced work environment and are looking for a rewarding career, then we want you on the team.\nWhat you can expect from working at OpenNet?\n1. Interesting and engaging work\n2. Incredibly talented co-workers\n3. Collaborative and flexible workplace\n4. World-class benefits package', datetime.datetime(2025, 12, 5, 10, 38, 47))

In [3]:
# ==================== 範例 2.2: 使用 pandas 讀取 SELECT 結果 ====================
# SQL 查詢語法（可修改條件）
query = f"SELECT job_title, salary, update_date FROM {TABLE} WHERE salary LIKE '%面議%' LIMIT 10"

# 使用 pandas 直接讀取
df = pd.read_sql(query, engine)
print("查詢結果（DataFrame）：")
display(df)  # 在 Notebook 中顯示表格

查詢結果（DataFrame）：

                                 job_title salary update_date
0                           技術工程類-AI自動化工程師   待遇面議      10月22日
1                  JC2002-軟體開發工程師(資料庫)-新竹區   待遇面議      10月22日
2                                  AI研發工程師   待遇面議      10月22日
3                                  數據分析工程師   待遇面議      10月22日
4                                【總部】程式設計師   待遇面議      10月22日
5           AI Application Engineer(竹南/台北)   待遇面議      10月22日
6          AI應用工程師 AI Application Engineer   待遇面議      10月22日
7  AI資料與分析工程師 AI Data & Analytics Engineer   待遇面議      10月22日
8           資料分析師 / Data Analyst - Tableau   待遇面議      10月22日
9                                AI 演算法工程師   待遇面議      10月22日

## 範例 3: 插入資料 (INSERT)

- 單筆插入。
- 多筆插入。

In [ ]:
# ==================== 範例 3.1: 單筆插入 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    # SQL 插入語法（假設 TABLE 有 id, job_title, salary 欄位；請根據實際 TABLE 調整）
    insert_query = f"INSERT INTO {TABLE} (job_title, salary, update_date) VALUES (%s, %s, %s)"
    data = ("測試職缺", "月薪 50,000", datetime.now().strftime('%Y-%m-%d'))  # 資料值
    
    cursor.execute(insert_query, data)
    conn.commit()  # 提交變更
    print(f"成功插入 1 筆資料，ID: {cursor.lastrowid}")
    
except Error as e:
    print(f"插入錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

In [ ]:
# ==================== 範例 3.2: 多筆插入 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    insert_query = f"INSERT INTO {TABLE} (job_title, salary, update_date) VALUES (%s, %s, %s)"
    data_list = [
        ("測試職缺1", "月薪 60,000", datetime.now().strftime('%Y-%m-%d')),
        ("測試職缺2", "月薪 70,000", datetime.now().strftime('%Y-%m-%d'))
    ]
    
    cursor.executemany(insert_query, data_list)
    conn.commit()
    print(f"成功插入 {cursor.rowcount} 筆資料")
    
except Error as e:
    print(f"插入錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 4: 更新資料 (UPDATE)

更新指定條件的資料。

In [ ]:
# ==================== 範例 4: 更新資料 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    # SQL 更新語法（假設有 id 欄位；請根據實際調整）
    update_query = f"UPDATE {TABLE} SET salary = %s WHERE job_title = %s"
    data = ("月薪 80,000", "測試職缺")  # 更新值與條件
    
    cursor.execute(update_query, data)
    conn.commit()
    print(f"成功更新 {cursor.rowcount} 筆資料")
    
except Error as e:
    print(f"更新錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 5: 刪除資料 (DELETE)

刪除指定條件的資料。

In [ ]:
# ==================== 範例 5: 刪除資料 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    # SQL 刪除語法（請小心使用，避免誤刪）
    delete_query = f"DELETE FROM {TABLE} WHERE job_title = %s"
    data = ("測試職缺",)  # 條件
    
    cursor.execute(delete_query, data)
    conn.commit()
    print(f"成功刪除 {cursor.rowcount} 筆資料")
    
except Error as e:
    print(f"刪除錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 6: 交易處理 (Transaction) - Commit & Rollback

使用交易確保資料一致性。

In [ ]:
# ==================== 範例 6: 交易處理 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    conn.autocommit = False  # 關閉自動提交，啟用手動交易
    cursor = conn.cursor()
    
    # 執行多個操作
    insert_query = f"INSERT INTO {TABLE} (job_title, salary, update_date) VALUES (%s, %s, %s)"
    cursor.execute(insert_query, ("交易測試", "月薪 90,000", datetime.now().strftime('%Y-%m-%d')))
    
    # 模擬錯誤（取消註解來測試 rollback）
    # raise Error("模擬錯誤")
    
    conn.commit()  # 成功則提交
    print("交易成功提交")
    
except Error as e:
    conn.rollback()  # 錯誤則回滾
    print(f"交易失敗，回滾: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 7: 使用 pandas 寫入資料 (to_sql)

將 DataFrame 直接寫入資料庫。

In [ ]:
# ==================== 範例 7: 使用 pandas 寫入資料 ====================
# 建立一個測試 DataFrame
data = {
    'job_title': ['Pandas測試1', 'Pandas測試2'],
    'salary': ['月薪 100,000', '月薪 110,000'],
    'update_date': [datetime.now().strftime('%Y-%m-%d'), datetime.now().strftime('%Y-%m-%d')]
}
df_write = pd.DataFrame(data)

# 寫入資料庫（if_exists='append' 表示附加，不覆蓋）
df_write.to_sql(TABLE, engine, if_exists='append', index=False)
print(f"成功寫入 {len(df_write)} 筆資料到 {TABLE}")

## 範例 8: 進階查詢 - 帶參數的查詢 (防止 SQL Injection)

使用參數化查詢以提升安全性。

In [ ]:
# ==================== 範例 8: 帶參數的查詢 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    # 參數化 SQL（防止 SQL Injection）
    query = f"SELECT * FROM {TABLE} WHERE job_title LIKE %s LIMIT 5"
    param = ("%測試%",)  # 查詢包含 '測試' 的職缺
    
    cursor.execute(query, param)
    results = cursor.fetchall()
    for row in results:
        print(row)
    
except Error as e:
    print(f"查詢錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 9: 建立新資料庫或表格 (CREATE)

示範建立新資料庫或表格。

In [ ]:
# ==================== 範例 9.1: 建立新資料庫 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD)
    cursor = conn.cursor()
    
    new_db = "test_database"  # 新資料庫名稱
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS {new_db}")
    print(f"成功建立資料庫: {new_db}")
    
except Error as e:
    print(f"建立錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

In [ ]:
# ==================== 範例 9.2: 建立新表格 ====================
try:
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    cursor = conn.cursor()
    
    new_table = "test_table"  # 新表格名稱
    create_query = f"""
        CREATE TABLE IF NOT EXISTS {new_table} (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255),
            created_at DATETIME
        )
    """
    cursor.execute(create_query)
    print(f"成功建立表格: {new_table}")
    
except Error as e:
    print(f"建立錯誤: {e}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()

## 範例 10: 資料庫結構檢查 (Database Inspection)

包含以下檢查項目：
- 列出所有資料庫 (SHOW DATABASES)
- 列出目前資料庫的所有表格 (SHOW TABLES)
- 檢查每個表格的資料筆數 (Row Count)
- 檢查每個表格的欄位資訊 (Schema/Columns)

In [7]:
# ==================== 範例 10: 資料庫結構檢查 ====================
try:
    # 1. 連線到 Server (不指定 Database 以便查看所有 DB)
    # 注意：需使用之前定義好的 HOST, USER, PASSWORD 變數
    conn = mysql.connector.connect(host=HOST, user=USER, password=PASSWORD)
    cursor = conn.cursor()

    print("\n--- 1. 列出所有資料庫 (SHOW DATABASES) ---")
    cursor.execute("SHOW DATABASES")
    dbs = cursor.fetchall()
    df_dbs = pd.DataFrame(dbs, columns=['Database Name'])
    display(df_dbs)

    # 2. 切換到指定資料庫並列出表格
    conn.database = DATABASE
    print(f"\n--- 2. 列出資料庫 '{DATABASE}' 中的所有表格 (SHOW TABLES) ---")
    cursor.execute("SHOW TABLES")
    tables = cursor.fetchall()
    # tables 是一個 list of tuples e.g., [('table1',), ('table2',)]
    table_names = [t[0] for t in tables]
    df_tables = pd.DataFrame(table_names, columns=['Table Name'])
    display(df_tables)

    # 3. 檢查每個表格的詳細資訊
    print("\n--- 3. 檢查每個表格的資料筆數與欄位資訊 ---")
    for table in table_names:
        print(f"\n========================================")
        print(f"表格名稱: {table}")
        
        # 查詢筆數
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        count = cursor.fetchone()[0]
        print(f"資料筆數: {count}")
        
        # 查詢欄位資訊 (使用 pandas read_sql 讀取 DESCRIBE)
        print("欄位結構:")
        df_schema = pd.read_sql(f"DESCRIBE {table}", conn)
        display(df_schema)

except Error as e:
    print(f"檢查錯誤: {e}")
finally:
    if 'conn' in locals() and conn.is_connected():
        cursor.close()
        conn.close()
        print("\n檢查完成，連線已關閉")

--- 1. 列出所有資料庫 (SHOW DATABASES) ---

        Database Name
0  information_schema
1             rawdata

--- 2. 列出資料庫 'rawdata' 中的所有表格 (SHOW TABLES) ---

        Table Name
0       104rawdata
1  all_jobs_master
2      job_details

--- 3. 檢查每個表格的資料筆數與欄位資訊 ---

========================================
表格名稱: 104rawdata
資料筆數: 13884
欄位結構:

C:\Users\fordi\AppData\Local\Temp\ipykernel_51784\4262808631.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_schema = pd.read_sql(f"DESCRIBE {table}", conn)

,Field,Type,Null,Key,Default,Extra
0,id,bigint(20),NO,PRI,None,auto_increment
1,job_id,varchar(20),NO,MUL,None,
2,job_title,varchar(200),NO,,None,
3,company,varchar(200),NO,MUL,None,
4,industry,varchar(100),YES,,None,
5,location,varchar(100),YES,MUL,None,
6,experience,varchar(50),YES,,None,
7,education,varchar(50),YES,,None,
8,salary,varchar(100),YES,MUL,None,
9,tags,text,YES,,None,
10,update_date,varchar(50),YES,,None,
11,job_description,longtext,YES,,None,
12,job_categories,varchar(200),YES,,None,
13,management_responsibility,varchar(100),YES,,None,
14,work_shift,varchar(100),YES,,None,
15,remote_work,text,YES,,None,
16,BT_EXP,varchar(100),YES,,None,
17,languages,text,YES,,None,
18,tools,text,YES,,None,
19,work_skills,text,YES,,None,
20,other_conditions,text,YES,,None,
21,raw_text,longtext,YES,,None,
22,created_at,datetime,YES,,current_timestamp(),
23,updated_at,datetime,YES,,current_timestamp(),on update current_timestamp()
24,update_date_clean,varchar(20),YES,,None,
25,unique_key,varchar(50),YES,UNI,None,

========================================
表格名稱: all_jobs_master
資料筆數: 14901
欄位結構:

C:\Users\fordi\AppData\Local\Temp\ipykernel_51784\4262808631.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_schema = pd.read_sql(f"DESCRIBE {table}", conn)

        Field          Type Null Key Default Extra
0       title  varchar(255)  YES        None
1     company  varchar(255)  YES        None
2    industry  varchar(255)  YES        None
3  salary_raw  varchar(255)  YES        None
4  avg_salary       int(11)  YES        None
5    location  varchar(255)  YES        None
6     content          text  YES        None
7      source   varchar(50)  YES        None
8         url          text  YES        None

========================================
表格名稱: job_details
資料筆數: 1017
欄位結構:

C:\Users\fordi\AppData\Local\Temp\ipykernel_51784\4262808631.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_schema = pd.read_sql(f"DESCRIBE {table}", conn)

,Field,Type,Null,Key,Default,Extra
0,id,int(11),NO,PRI,None,auto_increment
1,url,text,YES,,None,
2,job_title,varchar(255),YES,,None,
3,company,varchar(255),YES,,None,
4,industry,varchar(255),YES,,None,
5,category,varchar(255),YES,,None,
6,salary,varchar(255),YES,,None,
7,location,varchar(255),YES,,None,
8,experience,varchar(255),YES,,None,
9,job_type,varchar(50),YES,,None,
10,job_level,varchar(50),YES,,None,
11,hiring_count,varchar(50),YES,,None,
12,management,varchar(50),YES,,None,
13,remote,varchar(50),YES,,None,
14,original_tags,text,YES,,None,
15,analyzed_skills,text,YES,,None,
16,updated_date,varchar(50),YES,,None,
17,content,longtext,YES,,None,
18,created_at,timestamp,YES,,current_timestamp(),

檢查完成，連線已關閉

## 注意事項

- **安全性**：避免在程式碼中硬編碼密碼，建議使用環境變數或 secrets 管理。
- **錯誤處理**：每個範例都有 try-except 來捕捉錯誤。
- **效能**：對於大量資料，使用 pandas 或 chunksize 參數來分批處理。
- **自訂**：根據您的 TABLE 結構調整 SQL 語法中的欄位名稱。